# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      - name: Format
        run: make format

      - name: Lint
        run: make lint

      - name: Check
        run: git diff --exit-code
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test 01-hello-world
        run: |
          cd 01-hello-world && make generate && make build
          sudo timeout -s SIGINT --preserve-status 10 ./01-hello-world